Repository pantos-io/validatornode, pull requests merged in 2024-07, with the labels that each got.

#23 [PAN-2070] add blockchain check endpoint
  pantos/validatornode/application.py
  pantos/validatornode/configuration.py
  pantos/validatornode/restapi.py
  poetry.lock
  pyproject.toml
  tests/test_application.py
  tests/test_configuration.py
Labels: enhancement

#24 [PAN-1981] Business logic for off-chain transfer submission
  pantos/validatornode/business/transfers.py
  tests/business/transfers/test_confirm_transfer.py
  tests/business/transfers/test_detect_new_transfers.py
  tests/business/transfers/test_submit_transfer_onchain.py
  tests/business/transfers/test_submit_transfer_to_primary_node.py
  tests/business/transfers/test_validate_transfer.py
Labels: enhancement

#26 [PAN-1998] Upgrade to hexbytes 1.x
  pantos/validatornode/blockchains/ethereum.py
  poetry.lock
  pyproject.toml
  tests/blockchains/test_ethereum.py
Labels: dependencies

#28 Bump version to 1.8.2
  debian/changelog
  poetry.lock
  pyproject.toml
Labels: documentation

#30 [PAN-2082] Return transferTo signature as string
  pantos/validatornode/blockchains/ethereum.py
Labels: bug

#33 [PAN-2082] Improved retry resilience and increased gas
  Makefile
  pantos/validatornode/blockchains/ethereum.py
  pantos/validatornode/business/transfers.py
  poetry.lock
  pyproject.toml
  tests/business/transfers/test_submit_transfer_onchain.py
Labels: bug
